### ISSUE TITLE
Using native instruments.

### ISSUE THREAD

**Issue by aashlykov** [mvitlov/vscode-db-explorer-firebird#11]
Hello. Is there plans to use native client libraries (like libfbclient.so) or isql executable as the base of extension? At now it seems that extension do all work, so extension depend on server configuration (legacy auth) and it doesn't work at embedded mode. Using native instruments solves these problems and possibly reduces the amount of program code. Or will it be problematic?

**Comment by mvitlov** [comment]
Hi, unfortunately no plans to do that for now. I agree with you about the native libraries, however that would require to rewrite the extension from scratch, and time is short.
