### ISSUE TITLE
Not all tables shown

### ISSUE THREAD

**Issue by fabi1996** [mvitlov/vscode-db-explorer-firebird#6]
**Describe the bug**
The table-view does not show all tables

**To Reproduce**
Add database connection and check whether all tables are listed

**Expected behavior**
To see all tables

**Environment info (please complete the following information):**
 - VS Code version: 0.0.3
 - Firebird version: 2.5

**Comment by mvitlov** [comment]
The sql select that is currently used works just fine (tested locally on a db with 2000+ tables).
It's taken from official Firebird page: [FAQ](http://www.firebirdfaq.org/faq174/)

If not all tables are shown, please change the following extension setting:
`firebird.maxTablesCount: <number>` | Number of tables visible in database tree. (**Default is 10**)
