### ISSUE TITLE
SELECT bug after previous DELETE

### ISSUE THREAD

**Issue by Slipinir** [mvitlov/vscode-db-explorer-firebird#8]
SELECT bug after previous DELETE.

1. Fire a SELECT
2. Fire a DELETE
3. Fire another SELECT

Show up this error:
[17:56:19][vscode-db-explorer-firebird][ERROR] Cannot use 'in' operator to search for 'message' in undefined

![image](https://user-images.githubusercontent.com/7811014/53598049-7ec2e580-3b82-11e9-8b21-178094898934.png)

Version: 1.31.1 (user setup)
Commit: 1b8e8302e405050205e69b59abb3559592bb9e60
Date: 2019-02-12T02:20:54.427Z
Electron: 3.1.2
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134

**Comment by mvitlov** [comment]
@Slipinir Thank you for the bug report. The bug is solved in v0.0.4

Cheers!
