### ISSUE TITLE
Does not show all tables 

### ISSUE THREAD

**Issue by hoegge** [mvitlov/vscode-db-explorer-firebird#9]
Great extension. 

I have increased the max tables to 100 but still the extension does not show all tables in the three different databases I connect to on the same server.

**Comment by e-belair** [comment]
Same for me

**Comment by newskoe** [comment]
Same for me( Very sadly=(

**Comment by krcha** [comment]
same here

**Comment by mvitlov** [comment]
Hmm... I tested it with a production database with **2000+** tables, and it shows them all without problem.
Unfortunately, I can't help you further without reproducing a problem.

Can you try going into your vs code settings > firebird and set the **Log Level** to **ERROR**. Then please check the output on the extension channel to see if there are any errors there?

**Comment by hoegge** [comment]
Could it be related to having more than one database open on the same server at the same time?

**Comment by wdtbrchan** [comment]
This query returns all 250 tables but DB explorer shows only 60. 
No error/warning in the output log.

```
select rdb$relation_name
from rdb$relations
where 
rdb$view_blr is null
and (rdb$system_flag is null or rdb$system_flag = 0)
order by 1;

```

**Comment by wdtbrchan** [comment]
@mvitlov 
Probably the condition have to look like: COALESCE(RDB$RELATION_TYPE,0)=0
Because RDB$RELATION_TYPE=0 not list tables with RDB$RELATION_TYPE=NULL

**Comment by crisgol** [comment]
change  Firebird: Max Tables Count   to 1000
in menu file\ preferences\settings

**Comment by janbrchan** [comment]
Max Tables Count in settings doesnt work, the problem is rdb$system_flag is null

**Comment by wdtbrchan** [comment]
@crisgol 
Max Tables Count in settings doesnt work, the problem is probably rdb$system_flag is null and vscode-db-explorer-firebird selects only rdb$system_flag=0

**Comment by wdtbrchan** [comment]
this solves the issue 
https://github.com/fabi1996/vscode-db-explorer-firebird/commit/4a9416d8d15487a19675dba44982487dac587fb4
